version: "3.8"

services:

  db:
    build: 
      dockerfile: ./docker/db.dockerfile
      context: .
    image: vinnioh/pg_crud
    container_name: db
    ports: 
      - "5432:5432"
    networks: 
      - nwcrud
    volumes: 
      - pgdata:/var/lib/postgresql/data/

networks: 
  nwcrud:
    driver: bridge

volumes: 
  pgdata:
