version: "3.8"

services:

  db:
    build: 
      dockerfile: ./docker/db.dockerfile
      context: .
    image: vinnioh/pg_crud
    container_name: db
    ports: 
      - "5432:5432"
    networks: 
      - nwcrud
    volumes: 
      - pgdata:/var/lib/postgresql/data/


  pg-admin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"
    networks:
      - "nwcrud"
    depends_on:
      - "db"

  
networks: 
  nwcrud:
    driver: bridge

volumes: 
  pgdata:
